language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - g++
  - clang
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install cmake valgrind; fi

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc -DXML_PARSER_VERBOSE=On ..
  - make
after_script: 
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ../run-tests.sh; fi

