language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - g++
  - clang
before_install:
  - sudo apt-get update
  - sudo apt-get install cmake valgrind
script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc -DXML_PARSER_VERBOSE=On ..
  - make
after_script: ../run-tests.sh

